name: Bench

on: workflow_dispatch

env:
    CARGO_TERM_COLOR: always

jobs:
    bench:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # Don't forget to update `Cargo.toml`
            - name: Setup rust 1.87.0
              run: rustup toolchain install 1.87.0 --profile minimal --no-self-update
            - name: Bench
              if: matrix.os == 'ubuntu-latest'
              run: cargo bench
